### ISSUE TITLE
Create FFI struct for `PublicKey`

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe-client-libs#860]
Currently, when converting the FFI structs containing `safe_nd::PublicId`, we assume it's always `PublicId::Bls` and panic if that's not the case. Instead, this should be handled properly by having analogous FFI structure for PublicKey which should be able to hold keys of different types.

It is therefore proposed to have a `ffi::PublicKey` struct defined as follows:

```rust
// Corresponds to the `PublicKey` enum in safe_nd.
#[repr(C)]
pub enum PublicKeyType {
  Ed25519,
  Bls,
  BlsShare,
}

#[repr(C)]
pub union PublicKeyBytes {
  bls_key: [u8; BLS_KEY_LEN],
  bls_share: [u8; BLS_SHARE_LEN],
  ed25519_key: [u8; ED25519_LEN],
}

#[repr(C)]
pub struct PublicKey {
  type: PublicKeyType,
  key: PublicKeyBytes,
}

impl ReprC for safe_nd::PublicKey {
  type C = PublicKey;

  unsafe fn clone_from_repr_c(repr_c: Self::C) -> Result<Self, Self::Error> {
    match repr_c.type {
      PublicKeyType::Bls => safe_nd::PublicKey::Bls(threshold_crypto::PublicKey::from_bytes(repr_c.key.bls_key)),
      ..
    }
  }
}
```

In the languages not having support for `union`s the internal array can just be interpreted differently based on the tag.

**Comment by m-cat** [comment]
I think you intended this FFI struct to be defined in SCL (since you prefix `PublicKey` with `safe_nd::`), but I'm thinking `safe-nd` itself would be a better place for it:

1. We don't currently export the inner types of `PublicKey`, such as `ed25519_dalek::PublicKey`, so we would have to do so,
2. We can't implement `ReprC`, from `ffi_utils`, for `PublicKey`, from `safe-nd`, within SCL.
3. `PublicKey` may some day be used in FFI for crates that don't have anything to do with SCL.

Let me know what you think!

**Comment by nbaksalyar** [comment]
@m-cat, you're right, it should be defined in either `safe-nd` or `ffi_utils` itself.
I'm not sure exaclty which one though, having FFI in safe-nd would be a bit of a scope creep. :/
I think we should discuss and decide this later when we get to actually start implementing the new FFI.

**Comment by ravinderjangra** [comment]
Closing this issue as the FFI layer has been moved to the `safe-api` repo and doesn't expose low-level APIs for now.
